name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - master

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # For PyPI trusted publishing
      contents: write  # For creating GitHub releases
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Set version from tag
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        # Update version in __init__.py
        sed -i "s/__version__ = .*/__version__ = \"$VERSION\"/" src/CA/__init__.py
        # Update version in pyproject.toml
        sed -i "s/version = .*/version = \"$VERSION\"/" pyproject.toml

    - name: Build package
      run: python -m build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1 